# Generated by Django 6.0.3 on 2026-03-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50)),
                ('codigo', models.IntegerField(default=0)),
                ('quantidade', models.IntegerField(default=0)),
            ],
        ),
    ]
