# Generated by Django 6.0.3 on 2026-06-03 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logEasy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoExpedicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(max_length=100)),
                ('codigo_produto', models.IntegerField()),
                ('departamento_nome', models.CharField(max_length=50)),
                ('quantidade_retirada', models.IntegerField()),
                ('data_saida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='produtos',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='logEasy.departamento'),
        ),
    ]
